### PR TITLE
Near-Final Edit

### PR DESCRIPTION
**Pull request by lsmith2**
Just needs the training page put in and all the pages linked together

### CODE REVIEW

**Comment by jimcavoli** [comment]
I will look deeper at this a little later.
Note: up for preview at http://lsmith2.github.io/c4a-conclave/

**Comment by jimcavoli** [comment]
We're going to need to get rid of the blue-on-black; it has a contrast ratio of only 2.4:1 which is well below the WCAG minimum of 4.5:1 at our current font size. Part of the reason for the green I had used previously is that it boasts a 17:1 ratio, well above the 7:1 necessary for AAA rating. White, at a 21:1 ratio, is fine as well.

@lsmith2 could you remove the blue override and also refactor the code to not leave any inline `<style>` tags in the source?

**Comment by jimcavoli** [comment]
@lsmith2 I also just noticed that you seem to have removed the Code of Conduct and Cancellation Policy from the site. This content is required and will need to be restored in some capacity before we can merge.

**Comment by lsmith2** [comment]
@jimcavoli I've made the requested changes. Is there anything I forgot or also need to add?

**Pull request closed without merging**
